#!/bin/bash

rm -r Fdata_*
cd distorted_benzene

rm  Fdata fireball.in CHARGES NEIGHBORS* Atomo_* answer* modes.xyz struc.inp \
         *.out *.xsf *.dat

cd ../benzene_on_grid/

rm  Fdata fireball.in CHARGES NEIGHBORS* Atomo_* answer* modes.xyz struc.inp \
         *.out *.xsf *.dat

cd ../graphene_2x2/

rm  Fdata fireball.in CHARGES NEIGHBORS* Atomo_* answer* modes.xyz struc.inp \
         *.out *.xsf *.dat

cd ../graphene_grid/

rm  Fdata fireball.in CHARGES NEIGHBORS* Atomo_* answer* modes.xyz struc.inp \
         *.out *.xsf *.dat

#rm Fdata
#rm fireball.in
#rm CHARGES
#rm NEIGHBORS*
#rm *.out
#rm *.xsf
#rm Atomo_*
#rm *.dat
#rm answer*
#rm modes.xyz
#rm struc.inp
