# Generated by Django 3.2.13 on 2022-07-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='peticion',
            name='pub_date',
        ),
    ]
