# Generated by Django 3.2.13 on 2022-07-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220716_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peticion',
        ),
    ]
