! this module do nothing, just to compile fireball.x 
!+++++++++++++++++++++++++++++++++++++++++++++

module qmmm_module

  implicit none
  ! data structures
  public :: qmmm_struct, qmmm_nml
  
  
  type qmmm_structure
   double precision :: enuclr_qmqm, enuclr_qmmm !Calculated Core-Core energy for QM-QM nuclei-nuclei and QM nuclei - MM charge interactions.
                                      !in (eV)
   double precision :: elec_eng                 !Electronic energy (in eV)
   double precision, dimension(:), pointer :: qm_resp_charges  !Nquant long - contains the original resp charges for the
                                                         !QM atoms as read from the prmtop file.
   double precision :: qm_resp_charge_sum !Sum of the resp charges making up the quantum region. - In AMBERELECTROSTATIC UNITS
   double precision, dimension(:), pointer :: mm_link_pair_resp_charges
   double precision, dimension(:,:), pointer :: mm_link_pair_saved_coords !The coordinates of the mm link pair atoms as they would be for
                                                              !a given MD step in amber's unimaged coordinate array. Extracted
                                                              !by position link atoms and restored back
                                                              !into the x array by restore_mm_link_pair_coords.
   double precision, dimension(:,:), pointer :: qm_coords     !Cartesian coordinates of ALL (real+link) qm atoms [3*(nquant+nlink) long]
   double precision, dimension(:,:), pointer :: qm_vel        !Cartesian coordinates of ALL (real+link) qm atoms [3*(nquant+nlink) long
   double precision, dimension(:), pointer :: scaled_mm_charges !MM charges scaled by one scale to make them electron units
   double precision, dimension(:,:), pointer :: dxyzqm, dxyzcl  !Used to store the forces generated by qm_mm before adding them to the main f array.
   double precision, dimension(:,:), pointer :: qm_xcrd         !Contains imaged mm coordinates and scaled mm charges.
   double precision, dimension(:), pointer :: qm_xcrd_dist
   double precision, dimension(:,:), pointer :: scale_factor1_pm3mmx   ! Two params used in PM3/MM* calculations.
   double precision, dimension(:,:), pointer :: scale_factor2_pm3mmx   ! Two params used in PM3/MM* calculations.
   integer :: nquant    !Total number of quantum atoms (excluding link atoms).
   integer :: nlink     !Total number of link atoms
   integer :: nquant_nlink !Total number of quantum atoms = nquant+nlink
   integer :: qm_ntypes                           !The number of atom types present. 
                                                  !type, e.g. type 1 may have atomic number = 8.
   integer, dimension(:), pointer :: qm_atom_type !The type of each qm atom, essentially a re-basing of the
                                                  !atomic numbers to minimise memory usage.
  
   integer, dimension(:,:), pointer :: link_pairs ! list of MM-QM atoms for which link atoms were added
   integer, dimension(:), pointer :: iqm_atomic_numbers !integer list of atomic numbers for the qm atoms 
   integer                        :: qm_mm_pairs     !Number of pairs per QM atom. - length of pair_list. 
   integer, dimension(:), pointer :: qm_mm_pair_list !Non bond pair list for each QM atom
   integer, dimension(:), pointer :: all_atom_numbers !atomic numbers of ALL atoms (MM and QM)
   integer :: num_qmmm_calls       !Counter of the number of times qm_mm has been called - effectively nstep.
   integer :: prmtop_numbnd        !Number of bond types as read from the prmtop before any QM modifications
                                 !are made - needed to be able to call setbon multiple times and not have
                                 !new QM-H atom types keep being created.
   
  
   logical, dimension(:), pointer :: atom_mask !True / false mask specifying if atom is a QM atom. True = QM atom (natom long)
   logical, dimension(:), pointer :: mm_link_mask !True / false mask specifying if atom is a MM link pair atom. True = MM link pair atom (natom long)
   logical :: qm_mm_first_call !Set to true at beginning of sander subroutine and then set to false at the end of qm_mm. Used for allocation purposes.
   logical :: fock_first_call !Set to true at beginning of sander subroutine and then set to false at the end of qm_mm. Used for allocation purposes.
   logical :: fock2_2atm_first_call 
   logical :: qm2_allocate_e_repul_first_call
   logical :: qm2_calc_rij_eqns_first_call
   logical :: qm2_scf_first_call
   logical :: zero_link_charges_first_call
   logical :: adj_mm_link_pair_crd_first_call
   logical :: AM1_OR_PM3 !Set to True if theory is AM1, PM3, PDDG/PM3, PM3CARB1, RM1
   logical :: PDDG_IN_USE !Set to True if theory is PDDG/PM3 or PDDG/MNDO
   logical :: mmcoords_contains_lnk_coords !Set to true if the coordinates of the MM link pair atoms in 
                                           !ambers main coordinate array have been set to the link atom
                                           !coordinates. This acts as a safety to ensure that the adj 
                                           !link atoms is not called without having restored them.
   real , dimension(:), pointer :: Qresp ! cargas parciales de los atomos
   real , dimension(:), pointer :: Qneutral_TOT ! cargas parciales de los atomos


  end type qmmm_structure
  
  type ( qmmm_structure ) qmmm_struct
  
  type qm2_structure  !Variables that are specific to qm_routine=2 (qm2)
  
   !+TJG 01/26/2010   Not sure if this should be in qm
  
   double precision, dimension(:), pointer :: den_matrix      !The total density matrix
   double precision, dimension(:), pointer :: old_den_matrix  !The old total density matrix from preious step
                                                    !Allocated in qm2_load_params on first call - deallocated
                                                    !by deallocate_qmmm
   double precision, dimension(:), pointer :: old2_density  !Used by qm2_cnvg as workspace, norbs
  
   double precision, dimension(:), pointer :: md_den_mat_guess1 !These two guesses are only used when density_predict=1
   double precision, dimension(:), pointer :: md_den_mat_guess2 !They contain Pguess(t-1) and Pguess(t-2).
  
   double precision, dimension(:), pointer :: fock_mat_final4
   double precision, dimension(:), pointer :: fock_mat_final3
   double precision, dimension(:), pointer :: fock_mat_final2
   double precision, dimension(:), pointer :: fock_mat_final1 !These contain the final Fock matrices from previous MD steps.
                                                      !in the case of fock_predict=1 it contains the previous 4 MD step
                                                      !fock matrices. F4 = t-4, F3 = t-3, F2 = t-2, F1 = t-1.
  
   double precision, dimension(:), pointer :: fock_matrix     !Fock matrix
   double precision, dimension(:,:), pointer :: qm_mm_e_repul !Array containing the QM-MM electron repulsion integrals
   double precision, dimension(:), pointer :: qm_qm_2e_repul  !Array containing the QM-QM 2-electron repulsion integrals
                                                    !This is a big array, allocated by qm_mm and deallocated
                                                    !by deallocate_qmmm - it needs to be a total of n2el long.
   double precision, dimension(:), pointer :: hmatrix  !The 1-electron matrix - used by routines called from qm2_energy
                                             !allocated in qm_mm on first call - deallocated by  deallocate_qmmm
   double precision, dimension(:,:), pointer :: qm_qm_e_repul !Array containing the QM-QM electron repulsion integrals
                                                    !This was originally written as a file to disk in the energy
                                                    !routines and then re-read in the derivative routines. Now
                                                    !it is stored in memory. Allocated in qm_mm on first call
                                                    ! - deallocated by deallocate_qmmm
   double precision, dimension(:,:), pointer :: fock2_ptot2   !Used in qm2_fock2 routine - 16,nquant_nlink allocated in qm2_load_params
                                                    !deallocated in deallocate_qmmm
   double precision, dimension(:,:), pointer :: eigen_vectors !Holds the eigen vectors during the SCF - allocated in qm2_load_params
   double precision, dimension(:), pointer :: scf_mchg !Hold the mulliken charges at each scf step if calc_mchg_scf is true.
                                             !Otherwise only do it at the end of the scf.
  
  
   !+TJG 01/26/2010
   double precision, dimension(:,:), pointer :: diis_fock ! holds previous fock matrices for diis extrapolation
                                                ! matsize x ndiis
   double precision, dimension(:,:), pointer :: diis_errmat ! holds the previous error matrices for diis extrapolation
                                                ! matsize x ndiis
                                                ! The error matrices are antisymmetric
   double precision, dimension(:,:), pointer :: diis_mat  ! The diis extrapolation matrix.  The i,j element is the inner-product
                                                ! of error matrices (packed as vectors, e.g., the error vectors)
                                                ! The extra dimension enforces the constraint that the sum of
                                                ! extrapolation coefficients sum to unity
                                                ! ndiis+1 x ndiis+1
   !-TJG 01/26/2010
  
  
   integer :: matsize                        !Size of the various packed symmetric matrices. (norbs(norbs+1)/2)
   integer :: n2el                           !Number of 2 electron repulsion integrals, calculated by
                                             !moldat = 
                                             !50*nheavy(nheavy-1)+10*nheavy*nlight+(nlight*(nlight-1))/2
   integer :: norbs                          !Total Number of atomic orbitals.
   integer :: nclosed                        !Number of doubly occupied orbitals
   integer :: nopenclosed                    !Number of doubly occupied and singly occupied orbitals
   integer :: qm_mm_e_repul_allocated        !This was originally written as a file to disk in the energy
                                             !routines and then re-read in the derivative routines. Now
                                             !it is stored in memory. Allocated in qm_mm on first call
                                             !or if pair list changes too much. See qm_mm_e_repul array above
                                             ! - deallocated by deallocate_qmmm
   integer                         :: n_peptide_links !Number of peptide linkages in QM region to apply MM correction to.
   integer, dimension(:,:), pointer :: peptide_links !Identity of peptide linkages 4,n_peptide_linkages. 1 to 4 = H-N-C-O atom
                                                     !numbers.
   logical calc_mchg_scf                     !If set to true the mulliken charges will be calculated on each SCF iteration.
  end type qm2_structure

  type qmmm_namelist
   REAL :: qmcut     !Cutoff in angstroms for QM-MM electrostatics - default = same as MM-MM cutoff
   REAL :: qmcut2    !Cutoff^2i
  end type qmmm_namelist

  type ( qmmm_namelist ) qmmm_nml
  



end module qmmm_module

